language: elixir
elixir:
  - 1.7.4
  - 1.8.0
otp_release:
  - 19.3
  - 20.3
  - 21.2
matrix:
  allow_failures:
    - elixir: 1.8.0
    - elixir: 1.7.4
      otp_release: 21.2
  exclude:
    - elixir: 1.8.0
      otp_release: 19.3
env:
  - MIX_ENV=test
script: mix coveralls.travis
